name: Service2 Deploy

permissions:
  id-token: write
  contents: write
  pull-requests: write
  packages: read
on:
  push:
    branches: [ main ]
    paths:
      - "service1/**"
      - ".github/workflows/service1.yml"
  workflow_dispatch:
    inputs:
      stage:
        description: 'Stage to deploy to - for example, "dev" or "prod"'
        required: true
        default: 'dev'

jobs:
  lower-env-deploy:
    concurrency:
      group: svc2-lower-env-deploy
      cancel-in-progress: true
    name: Deploy Lower Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fake deploy
        run: echo "HI MOM"
  release-please:
    concurrency:
      group: svc2-release-please
      cancel-in-progress: true
    environment: release
    name: Release Please
    needs:
      - lower-env-deploy
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.service1--release_created }}
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          skip-github-pull-request: true
          skip-github-release: false
  prod-deploy:
    environment: prod
    concurrency:
      group: svc2-prod-deploy
      cancel-in-progress: true
    name: Deploy Prod
    needs:
      - release-please
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fake deploy
        run: echo "HI MOM"
